const BASE = 'https://gioriva.github.io/album/drone';

const ALBUMS = [
  {
    slug: "como-lake",
    name: "Como Lake",
    loc: "Lago · Como, Italia",
    coord: "IT · 45.81N 9.08E",
    photos: [
      "como-lake-01.jpg",
      "como-lake-02.jpg",
      "como-lake-03.jpg",
      "como-lake-04.jpg",
      "como-lake-05.jpg",
      "como-lake-06.jpg",
      "como-lake-07.jpg",
      "como-lake-08.jpg",
      "como-lake-09.jpg",
      "como-lake-10.jpg",
      "como-lake-11.jpg",
      "como-lake-12.jpg",
      "como-lake-13.jpg",
      "como-lake-14.jpg",
      "como-lake-15.jpg",
      "como-lake-16.jpg",
      "como-lake-17.jpg",
      "como-lake-18.jpg",
      "como-lake-19.jpg",
      "como-lake-20.jpg",
      "como-lake-21.jpg",
      "como-lake-22.jpg",
      "como-lake-23.jpg",
      "como-lake-24.jpg",
      "como-lake-25.jpg",
      "como-lake-26.jpg",
      "como-lake-27.jpg",
      "como-lake-28.jpg",
      "como-lake-29.jpg",
      "como-lake-30.jpg",
      "como-lake-31.jpg",
      "como-lake-32.jpg",
      "como-lake-33.jpg",
      "como-lake-34.jpg",
      "como-lake-35.jpg",
      "como-lake-36.jpg"
    ]
  },
  {
    slug: "como-by-night",
    name: "Como by Night",
    loc: "Lago · Notturno",
    coord: "IT · 45.81N 9.08E",
    photos: [
      "como-by-night-01.jpg",
      "como-by-night-02.jpg",
      "como-by-night-03.jpg",
      "como-by-night-04.jpg",
      "como-by-night-05.jpg",
      "como-by-night-06.jpg",
      "como-by-night-07.jpg",
      "como-by-night-08.jpg",
      "como-by-night-09.jpg",
      "como-by-night-10.jpg",
      "como-by-night-11.jpg",
      "como-by-night-12.jpg",
      "como-by-night-13.jpg",
      "como-by-night-14.jpg",
      "como-by-night-15.jpg",
      "como-by-night-16.jpg",
      "como-by-night-17.jpg",
      "como-by-night-18.jpg",
      "como-by-night-19.jpg"
    ]
  },
  {
    slug: "balbianello",
    name: "Balbianello",
    loc: "Villa · Lago di Como",
    coord: "IT · 45.96N 9.20E",
    photos: [
      "balbianello-01.jpg",
      "balbianello-02.jpg",
      "balbianello-03.jpg",
      "balbianello-04.jpg",
      "balbianello-05.jpg",
      "balbianello-06.jpg",
      "balbianello-07.jpg",
      "balbianello-08.jpg",
      "balbianello-09.jpg"
    ]
  },
  {
    slug: "cernobbio",
    name: "Cernobbio",
    loc: "Lago · Como, Italia",
    coord: "IT · 45.84N 9.07E",
    photos: [
      "cernobbio-01.jpg",
      "cernobbio-02.jpg",
      "cernobbio-03.jpg",
      "cernobbio-04.jpg",
      "cernobbio-05.jpg",
      "cernobbio-06.jpg",
      "cernobbio-07.jpg",
      "cernobbio-08.jpg",
      "cernobbio-09.jpg",
      "cernobbio-10.jpg",
      "cernobbio-11.jpg"
    ]
  },
  {
    slug: "faro-voltiano",
    name: "Faro Voltiano",
    loc: "Faro · Brunate, Como",
    coord: "IT · 45.83N 9.09E",
    photos: [
      "faro-voltiano-01.jpg",
      "faro-voltiano-02.jpg",
      "faro-voltiano-03.jpg",
      "faro-voltiano-04.jpg",
      "faro-voltiano-05.jpg",
      "faro-voltiano-06.jpg",
      "faro-voltiano-07.jpg"
    ]
  },
  {
    slug: "fireworks",
    name: "Fireworks",
    loc: "Fuochi · Notturno",
    coord: "IT · Show aereo",
    video: "HxWURr55VAE",
    photos: [
      "fireworks-01.jpg",
      "fireworks-02.jpg",
      "fireworks-03.jpg",
      "fireworks-04.jpg",
      "fireworks-05.jpg",
      "fireworks-06.jpg",
      "fireworks-07.jpg",
      "fireworks-08.jpg",
      "fireworks-09.jpg",
      "fireworks-10.jpg"
    ]
  },
  {
    slug: "varigotti",
    name: "Varigotti",
    loc: "Costa · Liguria",
    coord: "IT · 44.18N 8.40E",
    photos: [
      "varigotti-01.jpg",
      "varigotti-02.jpg",
      "varigotti-03.jpg",
      "varigotti-04.jpg",
      "varigotti-05.jpg",
      "varigotti-06.jpg",
      "varigotti-07.jpg",
      "varigotti-08.jpg",
      "varigotti-09.jpg",
      "varigotti-10.jpg",
      "varigotti-11.jpg",
      "varigotti-12.jpg",
      "varigotti-13.jpg",
      "varigotti-14.jpg",
      "varigotti-15.jpg",
      "varigotti-16.jpg",
      "varigotti-17.jpg",
      "varigotti-18.jpg",
      "varigotti-19.jpg",
      "varigotti-20.jpg",
      "varigotti-21.jpg",
      "varigotti-22.jpg",
      "varigotti-23.jpg",
      "varigotti-24.jpg",
      "varigotti-25.jpg",
      "varigotti-26.jpg",
      "varigotti-27.jpg",
      "varigotti-28.jpg",
      "varigotti-29.jpg",
      "varigotti-30.jpg"
    ]
  },
  {
    slug: "eze-sur-mer",
    name: "Eze-sur-Mer",
    loc: "Costa · Costa Azzurra",
    coord: "FR · 43.71N 7.36E",
    photos: [
      "eze-sur-mer-01.jpg",
      "eze-sur-mer-02.jpg",
      "eze-sur-mer-03.jpg",
      "eze-sur-mer-04.jpg",
      "eze-sur-mer-05.jpg",
      "eze-sur-mer-06.jpg",
      "eze-sur-mer-07.jpg",
      "eze-sur-mer-08.jpg",
      "eze-sur-mer-09.jpg",
      "eze-sur-mer-10.jpg"
    ]
  },
  {
    slug: "cannes",
    name: "Cannes",
    loc: "Città · Alpi Marittime",
    coord: "FR · 43.55N 7.01E",
    photos: [
      "cannes-01.jpg",
      "cannes-02.jpg",
      "cannes-03.jpg",
      "cannes-04.jpg",
      "cannes-05.jpg",
      "cannes-06.jpg",
      "cannes-07.jpg",
      "cannes-08.jpg",
      "cannes-09.jpg",
      "cannes-10.jpg",
      "cannes-11.jpg",
      "cannes-12.jpg",
      "cannes-13.jpg",
      "cannes-14.jpg",
      "cannes-15.jpg",
      "cannes-16.jpg",
      "cannes-17.jpg",
      "cannes-18.jpg",
      "cannes-19.jpg",
      "cannes-20.jpg",
      "cannes-21.jpg",
      "cannes-22.jpg",
      "cannes-23.jpg",
      "cannes-24.jpg",
      "cannes-25.jpg"
    ]
  },
];

function photoUrl(album, file) { return BASE + "/" + album.slug + "/" + file; }